### ISSUE TITLE
Pico Pi W possibilities?

### ISSUE THREAD

**Issue by PratikPramanik** [webhdx/PicoBoot#34]
| Answer some general questions first                             	|  	|
|:-------------------------------------------------------------------	|:------:	|
| Are you my GitHub sponsor? | no 	|
| Did you check older issues to see if it was requested before? | yes 	|

Note: I'm down to help work on this. 
What are the possibilities for Pico Pi W? Does anyone have the protocol for the Broadband Adapter mapped out that we can reference?

**Comment by webhdx** [comment]
I don't think PIco W will be able to emulate a BBA. It's too slow for that. Don't overestimate the capabilities of a small IoT module. It's not going to replace a proper 100Mbps NIC. Also BBA doesn't use "a protocol", if you wanted to emulate it you need to emulate register access which is partially documented in YAGCD. You can also reference the source code for Dolphin and Nintendont.

We should rather focus on more realistic goals and I think what should be fully doable is writing a firmware that will allow accessing CYW43439 from homebrew on GC. This will open up new possibilities to existing homebrew apps like automatic updates or even creating a completely new homebrew browser to update and download new software on the console. 

I started working on Pico W compatibility but it'll take a lot of time until it's ready. If you really want to help I have a TODO list of things that should be done before we even think of Pico W specific features:
* get rid of a workaround to duplicate bits in the payload or at least minimize it to 2 bits instead of 4
* write a small first stage loader that will load a DOL file from PicoBoot's memory so we can fully separate the firmware and loader from actual BS2 we are using (iplboot)
