### ISSUE TITLE
HDMI adapter in digital port is causing Picoboot to only boot once.

### ISSUE THREAD

**Issue by TheANTO83** [webhdx/PicoBoot#97]
| Answer some general questions first                             	  |  	     |
|:-------------------------------------------------------------------	|:------:|
| Which firmware version are you using?                             	| v0.2 |
| Are you using the official Raspberry Pi Pico board?                 | yes |
DOL001
AUS Power supply

My DOL001 system Boots Pico and operates Swiss 100% fine until the system is power cycle\ reset \ igr. Once the system is turned on a second time it will always boot back to the vanilla GameCube menu. I have found that is my Generic HDMI adapter is whats causing the issue. If i remove and reinsert the HDMI adapter then Picoboot will boot again, however it will only boot the first time again. When using OG Composite cables Picoboot runs flawlessly.

I have conducted my testing with under-gauge wires and with 26 gauge and also larger with no change in result.

Any suggestions why removing a HDMI adapter would cause Picoboot to work again?

**Comment by webhdx** [comment]
You may want to read some older issues describing the same problem. Try different power supply or if you have another GameCube you might try replacing power regulation board (it's below main logic board). Your problems comes from unstable power delivery caused by failing electrolytic capacitors. It's recommended to replace the caps in the PSU and on the power regulation board. Alternatively you can try hooking up Pico to 5V instead of 3.3V as described here: https://github.com/webhdx/PicoBoot/issues/75#issuecomment-1539225503

**Comment by TheANTO83** [comment]
Thanks Webhdx, I used 5v instead and everything works like a charm! cheers!

**Comment by webhdx** [comment]
Good to know. I'll probably change the wiring to use 5V instead of 3.3V in the future. It seems to be more reliable in case of worn power supplies.
